parameters: 
  environment: ''
  artifactName: ''
  azureSubscriptionName: ''
  azureSubscriptionId: ''

jobs:
- deployment: deploy_to_${{ parameters.environment }}
  displayName: Deploy to ${{ parameters.environment }}
  continueOnError: false
  workspace:
    clean: outputs
  environment: ${{ parameters.environment }}
  strategy:
    runOnce:
      deploy:      
        steps:

        - script: |
            FILE=$(Pipeline.Workspace)/${{ parameters.artifactName }}/pre-post-deployment-script.ps1
            if ! test -f "$FILE"
            then
              echo 'Do not execute'
              echo '##vso[task.setvariable variable=publish]False'
            else
              echo 'Will Execute'
              echo '##vso[task.setvariable variable=publish]True'
            fi
          displayName: 'Check for files in artifact'

        - task: AzurePowerShell@5
          condition: eq(variables.publish,True)
          displayName: Pre-deployment - Stop all active triggers
          inputs:
            azureSubscription: '${{ parameters.azureSubscriptionName }}'
            ScriptType: 'FilePath'
            ScriptPath: '$(Pipeline.Workspace)/${{ parameters.artifactName }}/pre-post-deployment-script.ps1'
            ScriptArguments: '-armTemplate $(Pipeline.Workspace)/${{ parameters.artifactName }}/oslo-adf-dev/ARMTemplateForFactory.json -resourceGroupName oslo-rg-${{ parameters.environment }} -DataFactoryName oslo-adf-${{ parameters.environment }} -preDeployment $true'
            azurePowerShellVersion: 'LatestVersion'
            
        - task: AzureResourceManagerTemplateDeployment@3
          displayName: Azure Deployment:Create Or Update Resource Group action on oslo-rg-${{ parameters.environment }}
          condition: eq(variables.publish,True)
          inputs:
            deploymentScope: 'Resource Group'
            azureResourceManagerConnection: '${{ parameters.azureSubscriptionName }}'
            subscriptionId: '${{ parameters.azureSubscriptionId }}'
            action: 'Create Or Update Resource Group'
            resourceGroupName: 'oslo-rg-${{ parameters.environment }}'
            location: 'West Europe'
            templateLocation: 'Linked artifact'
            csmFile: '$(Pipeline.Workspace)/${{ parameters.artifactName }}/oslo-adf-dev/ARMTemplateForFactory.json'
            csmParametersFile: '$(Pipeline.Workspace)/${{ parameters.artifactName }}/oslo-adf-dev/ARMTemplateParametersForFactory.json'
            overrideParameters: '-factoryName "oslo-adf-${{ parameters.environment }}" -oslo_kv_properties_typeProperties_baseUrl "https://oslo-kv-${{ parameters.environment }}.vault.azure.net/"'
            deploymentMode: 'Incremental'

        - task: AzurePowerShell@5
          displayName: Post-deployment - Delete removed objects. Start all active triggers
          condition: eq(variables.publish,True)
          inputs:
            azureSubscription: '${{ parameters.azureSubscriptionName }}'
            ScriptType: 'FilePath'
            ScriptPath: '$(Pipeline.Workspace)/${{ parameters.artifactName }}/pre-post-deployment-script.ps1'
            ScriptArguments: '-armTemplate $(Pipeline.Workspace)/${{ parameters.artifactName }}/oslo-adf-dev/ARMTemplateForFactory.json -resourceGroupName oslo-rg-${{ parameters.environment }} -DataFactoryName oslo-adf-${{ parameters.environment }} -preDeployment $false'
            azurePowerShellVersion: 'LatestVersion'